ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('guitars.urls')),
    path('users/', include('users.urls')),
    path('payments/', include('payments.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

guitars/urls.py
from django.urls import path
from . import views

app_name = 'guitars'

urlpatterns = [
    path(
        route='',
        view=views.index,
        name='index',
    ),
    path(
        route='guitar/<int:id_guitar>/',
        view=views.detail_guitar,
        name='detail_guitar',
    ),
    path(
        route='guitar/favorites/',
        view=views.favorites,
        name='favorites',
    ),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    #View SIGNUP
    path(
        route='signup/',
        view=views.view_signup,
        name='signup',
    ),
    #View LOGIN
    path(
        route='login/',
        view=views.view_login,
        name='login',
    ),
    #View LOGOUT
    path(
        route='logout/',
        view=views.view_logout,
        name='logout',
    ),
    #View UPDATE_PROFILE
    path(
        route='update-profile/',
        view=views.view_update_profile,
        name='update_profile',
    ),
]

guitars/models.py
from email.mime import image
from django.db import models

# Create your models here.
class Brand(models.Model):
    id_brand = models.AutoField(primary_key=True)
    name_company = models.CharField(max_length=45)
    website_address = models.CharField(max_length=100)
    origin = models.CharField(max_length=30)

    def __str__(self) -> str:
        return self.name_company

class Category(models.Model):
    id_category = models.AutoField(primary_key=True)
    name_category = models.CharField(max_length=45)

    def __str__(self) -> str:
        return self.name_category

class Model(models.Model):
    id_model = models.AutoField(primary_key=True)
    name_model = models.CharField(max_length=45)
    launch_year = models.IntegerField()
    number_copies = models.IntegerField()
    id_fk_brand = models.ForeignKey(Brand, on_delete=models.CASCADE, db_column='id_fk_brand')

    def __str__(self) -> str:
        return self.name_model

class Guitar(models.Model):
    id_guitar = models.AutoField(primary_key=True)
    name_guitar = models.CharField(max_length=100)
    size = models.IntegerField()
    weight = models.IntegerField()
    color = models.CharField(max_length=45)
    material = models.CharField(max_length=45)
    date_sale = models.DateField()
    price = models.DecimalField(max_digits=7, decimal_places=2)
    favorite = models.BooleanField(blank=False, default=False)
    image = models.ImageField(null=True, blank=True,upload_to='guitars/static/guitars/images')
    id_fk_model = models.ForeignKey(Model, on_delete=models.CASCADE, db_column='id_fk_model')
    id_fk_category = models.ForeignKey(Category, on_delete=models.CASCADE, db_column='id_fk_category')

    def __str__(self) -> str:
        return self.name_guitar
    
    def specs(self):
        my_model = Model.objects.get(pk=self.id_fk_model.id_model)
        my_brand = Brand.objects.get(pk=my_model.id_fk_brand.id_brand)
        context = {
            "id_brand": my_brand.id_brand,
            "name_brand":my_brand.name_company,
            "id_model":my_model.id_model,
            "name_model":my_model.name_model,
        }
        return context
    
    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url
    
class ImagesGuitar(models.Model):
    image = models.ImageField(null=True, blank=True,upload_to='guitars/static/guitars/images')
    id_fk_guitar = models.ForeignKey(Guitar, on_delete=models.CASCADE, related_name='images')
    
    def __str__(self):
        name = self.guitar.name_guitar + ", ID image: " + str(self.pk)
        return name
    
    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

guitars/views.py
from operator import truediv
from users.models import Profile
from payments.models import Order
from .models import Guitar, Model, Brand, Category
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
import json
from .utils import get_favs

# Create your views here.
def index(request):
    guitars = Guitar.objects.order_by('id_guitar')
    models = Model.objects.order_by('id_model')
    brands  = Brand.objects.order_by('id_brand')
    if not request.user.is_authenticated:
        context = {
            'list_guitars': guitars,
            'list_models': models,
            'list_brands': brands,
            'cartItems': 0,
        }
        return render(request, 'guitars/index.html', context)
    else:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        context = {
            'authenticated': True,
            'list_guitars': guitars,
            'list_models': models,
            'list_brands': brands,
            'cartItems': order.get_cart_items,
        }
        return render(request, 'guitars/index.html', context)

def detail_guitar(request, id_guitar):
    guitar = Guitar.objects.get(id_guitar=id_guitar)
    if not request.user.is_authenticated:
        context = {
            'guitar': guitar,
            'cartItems': 0,
        }
        return render(request, 'guitars/detail_guitar.html', context)
    else:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        context = {
            'guitar': guitar,
            'cartItems': order.get_cart_items,
        }
        return render(request, 'guitars/detail_guitar.html', context)
    

@login_required(login_url='/users/login/')
def favorites(request):
    user = request.user
    myprofile = Profile.objects.get(user=user)
    try:
        if len(request.COOKIES.get('fav')) > 0:
            dict_fav_guitars = get_favs(request.COOKIES.get('fav').strip())
            for fav_guitar in dict_fav_guitars.items():
                if (fav_guitar[1] == "true"):
                    myprofile.addFavorite(fav_guitar[0])
                elif(fav_guitar[1] == "false"):
                    myprofile.removeFavorite(fav_guitar[0])
            myprofile.save()
    except:
        raise Exception("Error in Favorites View")

    customer = request.user.customer
    fav_guitars = []
    for favs in myprofile.getFavorites():
        fav_guitars.append(Guitar.objects.get(pk=favs))
    order, created = Order.objects.get_or_create(customer=customer, complete=False)
    context = {
        'fav_guitars': fav_guitars,
        'cartItems': order.get_cart_items,
        'error': "There are no guitars in your Favorite list"
    }
    return render(request, 'guitars/favorite.html', context)

guitars/templates/guitars/detail_guitar.html
{% extends 'main.html' %}
{% load static %}
{% block content %}

<section class="detail_guitar_container">
    <div class="buttons-detail-guitar">

		<a  
		class="btn btn-index" 
		href="{% url 'guitars:index' %}"
		>
			&#x2190; Continue Shopping
		</a>
		<button 
            data-product="{{ guitar.id_guitar }}" 
            data-action="add" 
            class="btn btn-outline-secondary add-btn update-cart"
        >
            Add to Cart
        </button>
	</div>
    <div class="title">
        <p>{{ guitar.name_guitar }}</p>
    </div>
    <div class="collage">

        
        {% for myimage in guitar.images.all %}
            <div class="item-carrusel" id="figure-0{{ forloop.counter }}">
                <figure>
                    <img src="{{ myimage.imageURL }}" alt="Imagen {{ forloop.counter }}">
                    
                </figure>
                <div class="navigation-arrow">
                    {% if forloop.counter == 1 %}
                        <a href="#figure-0{{ guitar.images.all|length }}">
                            <img class="left-arrow" src="{% static 'guitars/images/arrow-left.png' %}" alt="left-arrow">
                        </a>
                        <a href="#figure-0{{ forloop.counter|add:'1' }}">
                            <img class="right-arrow" src="{% static 'guitars/images/arrow-right.png' %}" alt="right-arrow">
                        </a>
                    {% elif forloop.counter == guitar.images.all|length %}
                        <a href="#figure-0{{ forloop.counter|add:'-1' }}">
                            <img class="left-arrow" src="{% static 'guitars/images/arrow-left.png' %}" alt="left-arrow">
                        </a>
                        <a href="#figure-01">
                            <img class="right-arrow" src="{% static 'guitars/images/arrow-right.png' %}" alt="right-arrow">
                        </a>
                    {% else %}
                        <a href="#figure-0{{ forloop.counter|add:'-1' }}">
                            <img class="left-arrow" src="{% static 'guitars/images/arrow-left.png' %}" alt="left-arrow">
                        </a>
                        <a href="#figure-0{{ forloop.counter|add:'1' }}">
                            <img class="right-arrow" src="{% static 'guitars/images/arrow-right.png' %}" alt="right-arrow">
                        </a>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>

    <div  class="features">
        <div class="title">
            <p>Caracteristicas principales</p>
        </div>
        <table>
            <thead>
                <tr>
                    <th>Feature</th>
                    <th>Value</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Brand</td>
                    <td>{{ guitar.specs.name_brand }}</td>
                </tr>
                <tr>
                    <td>Model</td>
                    <td>{{ guitar.specs.name_model }}</td>
                </tr>
                <tr>
                    <td>Material</td>
                    <td>{{ guitar.material }}</td>
                </tr>
                <tr>
                    <td>Release year</td>
                    <td>{{ guitar.date_sale }}</td>
                </tr>
                <tr>
                    <td>Main hand</td>
                    <td>Left/Right</td>
                </tr>
                <tr>
                    <td>Size</td>
                    <td>{{ guitar.size }} cm</td>
                </tr>
                <tr>
                    <td>Weight</td>
                    <td>{{ guitar.weight }} grams</td>
                </tr>
                <tr>
                    <td>Price</td>
                    <td>$ {{ guitar.price }} USD</td>
                </tr>
            </tbody>
        </table>
    </div>
</section>

{% endblock content %}

guitars/templates/guitars/favorite.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
    
    <section class="container-fav">

        <table class="table-articles">
            <thead>
                <tr>
                    <th>Image</th>
                    <th>Item</th>
                    <th>Price</th>
                    <th>Options</th>
                </tr>
            </thead>
            <tbody>
                {% for item in fav_guitars %}
                <tr>
                    <td><img class="row-image" src="{{ item.images.first.imageURL }}"></td>
                    <td class="name-item"><p>{{ item.name_guitar }}</p></td>
                    <td>${{item.price|floatformat:2}}</td>
                    <td>
                        <a  
                        class="btn-fav btn-favs" data-action="add-fav" data-product="{{ item.id_guitar }}" data-value="true"
                        href="{% url 'guitars:favorites' %}"
                        >
                            Remove Favorites
                        </a> <br>
                        <a  
                        data-product="{{ item.id_guitar }}" data-action="add"
                        class="btn btn-favs btn-outline-secondary add-btn update-cart"
                        >
                            Add to cart
                        </a> <br>
                        <a  
                        class="btn-favs" 
                        href="{% url 'guitars:detail_guitar' item.id_guitar %}"
                        >
                            View Details
                        </a>
                    </td>
                </tr>
            {%endfor%}
            </tbody>
        </table>
    </section>
    <script>
        document.cookie = 'fav=' + JSON.stringify(fav) + ";domain=;path=/";
    </script>
{% endblock content %}

guitars/templates/guitars/index.html
{% extends 'main.html' %}
{% load static %}
{% block content %}

<section class="index-container">

    <ul class="filter-guitars">

        <li class="container-filter">

            <div class="title-filter">
                <label class="label-content" for="title-filter">Show/Hide Filter</label>  
                <input class="cb" type="checkbox" id="title-filter">
                <label class="label-switch" for="title-filter"></label>         
            </div>
            <div class="all-filter hidden" id="div-all-filter">
                <label class="label-content" for="select-all">Select all</label>
                <input class="cb" type="checkbox" id="select-all" checked>
                <label class="label-switch" for="select-all"></label>
            </div>

            <ul class="options_brands hidden" id="ul_opt_brands">
                {% for mybrand in list_brands %}
                <li class="list-brand">
                    <label class="label-content" for="brand-{{ mybrand.id_brand }}">{{ mybrand.name_company|capfirst }}</label>
                    <input type="checkbox" class="cb cb-brand" id="brand-{{ mybrand.id_brand }}" checked> 
                    <label class="label-switch" for="brand-{{ mybrand.id_brand }}"></label>

                    <ul class="options_models" data-brand="brand-{{ mybrand.id_brand }}">
                        <!-- aca va un hidden -->
                        {% for mymodel in list_models %}
                        {% if mybrand.id_brand == mymodel.id_fk_brand.id_brand %}
                        <li class="list_model">
                            <label class="label-content" for="model-{{ mymodel.id_model }}">{{ mymodel.name_model|capfirst }}</label>
                            <input id="model-{{ mymodel.id_model }}" type="checkbox" class="cb cb-model"
                            data-brand="brand-{{ mybrand.id_brand }}" checked>
                            <label class="label-switch" for="model-{{ mymodel.id_model }}"></label>
                        </li>
                        {% endif %}
                        {% endfor %}
                    </ul>

                </li>
                {% endfor %}
            </ul>

        </li>

    </ul>

    <div class="guitar-container">
        {% for guitar in list_guitars %}
            <div class="container-unique-guitar" data-brand="brand-{{ guitar.specs.id_brand }}"
                data-model="model-{{ guitar.specs.id_model }}">
                <figure class="box">
                    <img src="{{ guitar.images.first.imageURL }}" alt="Imagen de {{ guitar.name_guitar }}">
                    <figcaption>
                        {{ guitar.name_guitar }} <br><br>
                        Price: <strong>${{ guitar.price|floatformat:2 }}</strong>
                    </figcaption>
                    <button class="btn-fav" data-action="add-fav" data-product="{{ guitar.id_guitar }}" data-value="false">
                        <img src="{% static 'images/full-heart.png' %}" alt="Imagen agregar a favoritos">
                    </button>
                </figure>
                <div class="box-element product">
                    <button data-product="{{ guitar.id_guitar }}" data-action="add"
                        class="btn btn-outline-secondary add-btn update-cart">
                        Add to Cart
                    </button>
                    <a class="lnk-guitar" href="{% url 'guitars:detail_guitar' guitar.id_guitar %}">View</a>
                </div>
            </div>
        {% endfor %}
    </div>

</section>



{% endblock content %}