ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('guitars.urls')),
    path('users/', include('users.urls')),
    path('payments/', include('payments.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

guitars/urls.py
from django.urls import path
from . import views

app_name = 'guitars'

urlpatterns = [
    path(
        route='',
        view=views.index,
        name='index',
    ),
    path(
        route='guitar/<int:id_guitar>/',
        view=views.detail_guitar,
        name='detail_guitar',
    ),
    path(
        route='guitar/favorites/',
        view=views.favorites,
        name='favorites',
    ),
]

payments/urls.py
from django.urls import path
from . import views

app_name = 'payments'

urlpatterns = [
    path(
        route='cart/',
        view=views.cart,
        name='cart'
    ),
    path(
        route='checkout/',
        view=views.checkout,
        name='checkout'
    ),
    path(
        route='update_item/',
        view=views.updateItem,
        name='update_item'
    ),
    path(
        route='history/',
        view=views.history_order,
        name='history'
    ),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    #View SIGNUP
    path(
        route='signup/',
        view=views.view_signup,
        name='signup',
    ),
    #View LOGIN
    path(
        route='login/',
        view=views.view_login,
        name='login',
    ),
    #View LOGOUT
    path(
        route='logout/',
        view=views.view_logout,
        name='logout',
    ),
    #View UPDATE_PROFILE
    path(
        route='update-profile/',
        view=views.view_update_profile,
        name='update_profile',
    ),
]

payments/models.py
from django.contrib.auth.models import User
from django.db import models
from guitars.models import Guitar

# Create your models here.   
class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)
    payment_method = models.CharField(max_length=200,default="Credit Card")
    
    def __str__(self):
        return self.name

class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=100, null=True)
    
    def __str__(self):
        name = (f'ID: {self.pk}, Customer: {self.customer.name}')
        return name
    
    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total
    
    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total
        
class OrderItem(models.Model):
    product = models.ForeignKey(Guitar, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        name = (f'ID: {self.pk}, Name: {self.product.name_guitar}, Order: {self.order.pk}')
        return name
    
    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total
        
class ShippingAddress(models.Model):
	customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
	order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
	address = models.CharField(max_length=200, null=False)
	city = models.CharField(max_length=200, null=False)
	state = models.CharField(max_length=200, null=False)
	zipcode = models.CharField(max_length=200, null=False)
	date_added = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.address


payments/forms.py
from email.policy import default
from .models import ShippingAddress
from django import forms
import datetime

payment_methods =(
    ("Credit Card","Credit Card"),
    ("Debit Card","Debit Card"),
    ("PAYPAL","PAYPAL"),
    ("NETELLER","NETELLER"),
    ("Bank Transfer", "Bank Transfer"),
)

class form_shipping_information(forms.Form):
    name = forms.CharField(required=True,max_length=100,widget=forms.TextInput(attrs={'placeholder': 'Enter your name'}))
    last_name = forms.CharField(required=True,max_length=100,widget=forms.TextInput(attrs={'placeholder': 'Enter your last name'}))
    email = forms.EmailField(required=True,max_length=100,widget=forms.EmailInput(attrs={'placeholder': 'Enter an email'}))
    address = forms.CharField(max_length=100,required=True,widget=forms.TextInput(attrs={'placeholder': 'Enter a Address'}))
    city = forms.CharField(max_length=50,required=True,widget=forms.TextInput(attrs={'placeholder': 'Enter a city'}))
    state = forms.CharField(max_length=50,required=True,widget=forms.TextInput(attrs={'placeholder': 'Enter a state'}))
    postal_code = forms.IntegerField(required=True,widget=forms.TextInput(attrs={'placeholder': 'Enter a Postal Code'}))
    payment_method = forms.ChoiceField(choices=payment_methods,required=True)
    
    def save_data(self, customer, order):
        order.transaction_id = datetime.datetime.now().timestamp()
        order.complete = True
        order.save()
        
        customer.payment_method = self.cleaned_data['payment_method']
        customer.save()
        
        ShippingAddress.objects.create(
            customer = customer,
            order = order,
            address = self.cleaned_data['address'],
            city = self.cleaned_data['city'],
            state = self.cleaned_data['state'],
            zipcode = self.cleaned_data['postal_code'],
        )
        
        print('*****'*5)
        print('Orden Completada y Direccion CREADA')
        print('*****'*5)

payments/views.py
from django.shortcuts import render,redirect
from django.http import JsonResponse
import json
from .models import * 
from .utils import cartData
from guitars.models import Guitar
from .forms import form_shipping_information
from django.contrib.auth.decorators import login_required
# Create your views here.

def cart(request):
	data = cartData(request)

	cartItems = data['cartItems']
	order = data['order']
	items = data['items']

	context = {'items':items, 'order':order, 'cartItems':cartItems}
	return render(request, 'payments/cart.html', context)

def checkout(request):
    
    data = cartData(request)
    cartItems = data['cartItems']
    items = data['items']
    
    if request.method == 'POST':
        form = form_shipping_information(request.POST)
        if form.is_valid():
            if request.user.is_authenticated:
                customer = request.user.customer
                order, created = Order.objects.get_or_create(customer=customer, complete=False)
                cartItems = order.get_cart_items
            else:
                customer = Customer(user=None)
                customer.name = form.cleaned_data['name']
                customer.email = form.cleaned_data['email']
                customer.payment_method = form.cleaned_data['payment_method']
                customer.save()
                order, created = Order.objects.get_or_create(customer=customer, complete=False)
                for myitem in items:
                    myproduct = OrderItem(product=myitem['product'], order=order, quantity=myitem['quantity'])
                pass
            form.save_data(customer,order)
            return redirect('guitars:index')
        else:
            return render(request, 'payments/checkout.html', {'form':form,'cartItems':cartItems})
    else:
        form = form_shipping_information()
        return render(request, 'payments/checkout.html', {'form':form,'cartItems':cartItems})

def updateItem(request):
	data = json.loads(request.body)
	productId = data['productId']
	action = data['action']

	customer = request.user.customer
	product = Guitar.objects.get(id_guitar=productId)
	order, created = Order.objects.get_or_create(customer=customer, complete=False)
	orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

	if action == 'add':
		orderItem.quantity = (orderItem.quantity + 1)
	elif action == 'remove':
		orderItem.quantity = (orderItem.quantity - 1)

	orderItem.save()

	if orderItem.quantity <= 0:
		orderItem.delete()

	return JsonResponse('Item was added', safe=False)

@login_required
def history_order(request):
    customer = request.user.customer
    history_order = Order.objects.filter(customer=customer)
    order, created = Order.objects.get_or_create(customer=customer, complete=False)
    context = {
        'history_order': history_order,
        'cartItems': order.get_cart_items,
        'error': "There are no guitars in your Favorite list"
    }
    customer = request.user.customer
    
    return render(request, 'payments/history_order.html', context)

payments/templates/payments/cart.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
	<section class="main-container-cart">
		<section class="container-cart">

			<section class="buttons-cart">
	
				<a  
				class="btn btn-index" 
				href="{% url 'guitars:index' %}"
				>
					&#x2190; Continue Shopping
				</a>
				<a  
				class="btn btn-checkout" 
				href="{% url 'payments:checkout' %}"
				>
					Checkout
				</a>
		
			</section>
		
			<section class="summary">
				<div class="table-title">
					<p>
						Summary
					</p>
				</div>
				<table class="minitable">
					<tr>
						<td>TOTAL ITEMS</td>
						<td>{{ order.get_cart_items }}</td>
					</tr>
					<tr>
						<td>TOTAL PRICE</td>
						<td>${{ order.get_cart_total|floatformat:2 }}</td>
					</tr>
				</table>
			</section>
		
			<table class="table-articles">
				<thead>
					<tr>
						<th>Image</th>
						<th>Item</th>
						<th>Price</th>
						<th>Quantity</th>
						<th>Total</th>
					</tr>
				</thead>
				<tbody>
					{% for item in items %}
					<tr>
						<td><img class="row-image" src="{{ item.product.images.first.imageURL }}"></td>
						<td class="name-item"><p>{{ item.product }}</p></td>
						<td>${{item.product.price|floatformat:2}}</td>
						<td align="center">
							{{item.quantity}}
							<div class="quantity">
								
								<img 
									data-product="{{ item.product.id_guitar }}" 
									data-action="add" 
									class="chg-quantity update-cart" 
									src="{% static  'images/arrow-up.png' %}"
								>
								<img 
									data-product="{{ item.product.id_guitar }}" 
									data-action="remove" 
									class="chg-quantity update-cart" 
									src="{% static  'images/arrow-down.png' %}"
								>
								
							</div>
						</td>
						<td>${{item.get_total|floatformat:2}}</td>
					</tr>
				{%endfor%}
				</tbody>
			</table>
		</section>
	</section>

{% endblock content %}

payments/templates/payments/checkout.html
{% extends 'main.html' %}
{% load static %}
{% block content %}

	<section class="main-checkout">

		<div class="container-checkout">
			<header>Checkout</header>

			<form id="checkout-form" action="{% url 'payments:checkout' %}" method="post" enctype="multipart/form-data">
				{% csrf_token %}
				<div class="fields">
					{% for field in form %}
						<div class="fieldWrapper" id="wrapper-{{ field.html_name }}">
							{{ field.errors }}
							{{ field.label_tag }} {{ field }}
							{% if field.help_text %}
								<p class="help">{{ field.help_text|safe }}</p>
							{% endif %}
						</div>
					{% endfor %}
				</div>
				<input id="btn-continue" class="btn" type="button" value="Continue">
				<div class="box-payment hidden" id="payment-info">
					<input id="make-payment" class="btn" type="submit" value="Make Payment">
				</div>
			</form>
		</div>

	</section>

	<script type="text/javascript" src="{% static 'payments/js/checkout.js' %}"></script>
{% endblock content %}

payments/templates/payments/history_order.html
{% extends 'main.html' %}
{% load static %}
{% block content %}

    <section class="history-order">
        <h1><strong>ORDER HISTORY</strong></h1>
        <hr size="8px" color="black" />
        <br>
        <div class="order-list">
            {% for order in history_order %}
                <div>
                    <table class="table-data-history">
                        <tbody>
                            <tr>
                                <td>
                                    <strong class="title-history">
                                        Id of Order:
                                    </strong>
                                </td>
                                <td> {{ order.pk }} </td>
                            </tr>
                            <tr>
                                <td>
                                    <strong class="title-history">
                                        Date of Order:
                                    </strong>
                                </td>
                                <td> {{ order.date_ordered }} </td>
                            </tr>
                            <tr>
                                <td>
                                    <strong class="title-history">
                                        Is complete?:
                                    </strong>
                                </td>
                                <td> {{ order.complete }} </td>
                            </tr>
                            <tr>
                                <td>
                                    <strong class="title-history">
                                        Transaction of Order:
                                    </strong>
                                </td>
                                <td> {{ order.transaction_id }} </td>
                            </tr>
                            <tr>
                                <td>
                                    <strong class="title-history">
                                        Total amount:
                                    </strong>
                                </td>
                                <td> {{ order.get_cart_total }} </td>
                            </tr>
                            <tr>
                                <td>
                                    <strong class="title-history">
                                        Total Items:
                                    </strong>
                                </td>
                                <td> {{ order.get_cart_items }} </td>
                            </tr>
                        </tbody>
                    </table>
                    <br>
                    <table class="table-articles">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Quantity</th>
                                <th>Price</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in order.orderitem_set.all %}
                                <tr>
                                    <td> {{ item.product }} </td>
                                    <td> {{ item.quantity }} </td>
                                    <td> {{ item.get_total }} </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <br>
                    <!-- <hr size="8px" color="black" /> -->
                    <br>
                </div>
            {% endfor %}
        </div>
    </section>
        
{% endblock content %}